[[mainDesign]]
= Building Block Design

================================

================================

== Registrar Service

=== Overview and Purpose

The purpose of the registrar service is to register data products from either upstream data sources (such as Sentinel-2 data archives) into the Data Access Building Block and the Resource Catalougue Building Block where they are indexed for later access.

=== Software Reuse and Dependencies

This service is based upon the Registrar Service of the View Server software system, using its plugin system to allow for a registration also into the Resource Catalogue.

=== Interfaces

This service does not provide any interfaces.

=== Data

==== Configuration

This service uses a YAML based configuration to allow the highly configurable configuration from various data sources parsed using various schemas into the backends.

==== Data flow

The registrar is a server process, listening on a distributed queue for new registration requests coming in as paths to the respective item to be registered.
When such a registration request is passed via the queue, the respective data storage source will be determined and the relevant data and metadata files are read for a rudimentary classification of the to be registered item, which will be passed to all configured backends for a final registration of the item.

The registrar allows for various item schemes:

* Sentinel-2 L2A: This expects an unpacked Sentinel-2 Level 2A SAFE package as the path input. It will parse all product and granule related metadata and will register the product as a single item.
* STAC-Catalog: This scheme requires a path to a directory containing at least one `catalog.json` file that will be read and parsed for both sub-catalogs and/or referenced STAC items. All STAC items found this way will be registered into all the backends.

=== Applicable Resources

TODO

== Renderer Service

=== Overview and Purpose

This service allows to generate automatic renderings of the registered data items via various standardized interfaces.

=== Software Reuse and Dependencies

This service is based upon the Renderer Service of the View Server software system with only minor enhancements.

=== Interfaces

==== OGC Web Service (OWS) interfaces

===== Web Coverage Service (WMS)

===== Web Map Service (WMS)

===== OpenSearch

===== Admin Interface

=== Data

==== Configuration

The application configuration is stored in the Database service where, depending on the request, all relevant metadata is extracted and used in the rendering process.

==== Data flow

As a web service, the renderer awaits user requests which are then processed. For that, initial queries to the database service are made, which in turn deliver the information of what files are required to fulfill the request. In the ensuing process, these files, residing on an object storage or a mounted network file system are then accessed and the required portions extracted. Finally, the resulting image, or data files are returned to the caller.

=== Applicable Resources


== Cache Service

=== Overview and Purpose

The purpose of this service is to provide a caching layer for WMS interface of the renderer service, as they may be computationally costly to produce.
Caching can happen either beforehand (pre-seeded) or on demand (or a mixture of both), in order to even further improve performance, even for the first lookup.
Caching is performed on a tile basis for each registered dataset, using the time axis to distinguish the individiual scenes in a collection. In order to resolve the time axis, a connection to the database service is used.

=== Software Reuse and Dependencies

This service is realized using the COTS MapCache with a custom confugation.

=== Interfaces

This service exposes the WMS and WMTS OGC Web Services endpoints.

=== Data

==== Configuration

A single configuration file defines the cache behavior.

==== Data flow

Similarly to the renderer service, the cache service exposes an HTTP endpoint that dispatches requests for the provided OGC Web Services. Depending on the request, a database query may be involved in order to resolve the time axis.
Now it is checked, whether the tiles involved with the request are already cached or need to be rendered by the renderer service. Each tile that is missing in the cache is now requested from the renderer and subsequently cached in the backend, the configured object storage.
The final response is now merged from all intersecting tiles and returned to the client.

=== Applicable Resources


== Client Service

=== Overview and Purpose

This service provides a configured client to be run in a browser.

=== Software Reuse and Dependencies

The server software used is the open source software nginx, serving a pre-built and configured JavaScript application eoxc, which is in turn based on the mapping library OpenLayers.

=== Interfaces

This service provides an HTTP endpoint to retrieve the client files.

=== Data

==== Configuration



==== Data flow

When requested, the client JavaScript bundle is downloaded by the browser and the application is initialized. This application will connect to the endpoints of various services such as the cache and renderer, but also external sources for map base-, or overlay layer tiles. The requested map tiles and metadata will be visualized within the app or made available as a downloaded file.

=== Applicable Resources


== Registration Endpoint Service

=== Overview and Purpose

This service provides an HTTP interface for the registrar service, allowing authorized clients to start, and receive notice when the registration has finished.

=== Software Reuse and Dependencies

=== Interfaces

This component exposes a single HTTP endpoint, allowing registration requests to be sent against. User authentication in the form of a JWT is used to discern the internal queue and object storage information used. The location of the item to be registered is passed as a JSON structure.

=== Data

==== Configuration

==== Data flow

=== Applicable Resources

== Database Service

=== Overview and Purpose

=== Software Reuse and Dependencies

=== Interfaces

=== Data

==== Configuration

==== Data flow

=== Applicable Resources

== Queue Service

=== Overview and Purpose

This service serves as a central point of communication between the services of the data access building block. Various sets and lists are used to track incoming registration requests and their subsequent status.

=== Software Reuse and Dependencies

This service is a configured instance of the Redis COTS software.

=== Interfaces

This service provides a TCP based endpoint for all commands.

=== Data

==== Configuration

No additonal configuration is used beyond the default settings.

==== Data flow

`registration_queue`: this list based queue is used to buffer incoming registration requests. It is used as a FIFO (first-in-first-out) queue, so the earlier registration request is handled first.

`registered_set`: This set of strings collects all registration items that were successfully registered.
`failure_set`: This set contains all the paths of items that failed to register.

=== Applicable Resources

