sources:
  - type: s3
    name: name # TODO
    kwargs:
      bucket_name: null
      endpoint_url: https://cf2.cloudferro.com:8080
      access_key_id: 13063b9e02844e1fb2df5580fa914172
      secret_access_key: 12a6ff49786545a7917647f609e91d22
      # region: RegionOne
schemes:
  - type: stac-item
backends:
  - type: eoxserver
    filter:
    kwargs:
      instance_base_path: /var/www/pvs/dev
      instance_name: pvs_instance
      mapping:
            "":
              "": 
                collections:
                - !env '${COLLECTION}'
  - 
    kwargs:
      repository_database_uri: postgresql://postgres:mypass@catalogue-db/pycsw
    path: registrar_pycsw.backend.PycswBackend