name: Build and publish Registration Endpoint Docker image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: ./endpoint
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: eoepca/rm-data-access-registration-endpoint
          tag_with_ref: true
